version: '3.8'

services:
  # Backend API Service (NestJS)
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: task-management-api
    restart: unless-stopped
    environment:
      - DATABASE_PATH=/data/database.sqlite # Hardcoded internal path
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000 # Hardcoded internal port
    volumes:
      - sqlite_data:/data
    networks:
      - app-network

  # Frontend Web Server (Angular + Nginx)
  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    container_name: task-management-dashboard
    restart: unless-stopped
    ports:
      - '${DASHBOARD_PORT}:80' # Expose the app on the host machine
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data:
    driver: local
